server {

    listen 109.172.30.245:80 default_server;
    listen 109.172.30.245:443 ssl default_server;


    server_name _;

    ssl_certificate /etc/nginx/ssl-certs/parking.crt;
    ssl_certificate_key /etc/nginx/ssl-certs/parking.key;

    include /etc/nginx/fastpanel2-includes/letsencrypt.conf;

    location / {
        root /var/www;
        try_files /index.html =404;
    }

    access_log /var/log/nginx/parking.access.log;
}
