server {

    listen 109.172.30.245:443 quic reuseport;


    server_name --;

    ssl_certificate /etc/nginx/ssl-certs/parking.crt;
    ssl_certificate_key /etc/nginx/ssl-certs/parking.key;

    location / {
        return 444;
    }

    access_log /var/log/nginx/reuseport.access.log;
}
